# Generated by Django 5.1.2 on 2024-11-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=20)),
                ('book_no', models.IntegerField(blank=True, null=True)),
                ('chap_no', models.IntegerField(blank=True, null=True)),
                ('verse_no', models.IntegerField(blank=True, null=True)),
                ('book_text', models.TextField()),
            ],
        ),
    ]
