# Generated by Django 5.1.2 on 2024-11-07 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rhema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rhema', models.TextField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('bible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.bible')),
            ],
        ),
    ]
